#ifndef LIME_IQSTREAM_SIGNALS_H
#define LIME_IQSTREAM_SIGNALS_H

#include <stdint.h>

// Host to VSPA flags
enum HTV_Signal {
    HTV_SIGNAL_NONE = 0,
    HTV_SIGNAL_RXLANE0_PRIME = (1 << 1),
    HTV_SIGNAL_RXLANE1_PRIME = (1 << 2),
    HTV_SIGNAL_RXLANE2_PRIME = (1 << 3),
    HTV_SIGNAL_RXLANE3_PRIME = (1 << 4),
    HTV_SIGNAL_RXLANE0_TCD_PENDING = (1 << 5),
    HTV_SIGNAL_RXLANE1_TCD_PENDING = (1 << 6),
    HTV_SIGNAL_RXLANE2_TCD_PENDING = (1 << 7),
    HTV_SIGNAL_RXLANE3_TCD_PENDING = (1 << 8),
    HTV_SIGNAL_RXLANE0_ABORT = (1 << 9),
    HTV_SIGNAL_RXLANE1_ABORT = (1 << 10),
    HTV_SIGNAL_RXLANE2_ABORT = (1 << 11),
    HTV_SIGNAL_RXLANE3_ABORT = (1 << 12),
    HTV_SIGNAL_TXLANE0_PRIME = (1 << 13),
    HTV_SIGNAL_TXLANE0_TCD_PENDING = (1 << 14),
    HTV_SIGNAL_TXLANE0_ABORT = (1 << 15),
};

enum VTH_Signal {
    VTH_SIGNAL_NONE = 0,
    VTH_SIGNAL_RXLANE0_TCD_DONE = (1 << 5),
    VTH_SIGNAL_RXLANE1_TCD_DONE = (1 << 6),
    VTH_SIGNAL_RXLANE2_TCD_DONE = (1 << 7),
    VTH_SIGNAL_RXLANE3_TCD_DONE = (1 << 8),
    VTH_SIGNAL_TXLANE0_TCD_DONE = (1 << 14),
    VTH_SIGNAL_TXLANE0_COMPLETE = (1 << 15),
    VTH_SIGNAL_ERROR = (1 << 31),
};

void clear_htv_signal(uint32_t mask);
void vspa_to_host_signal(uint32_t flags);

#endif // LIME_IQSTREAM_SIGNALS_H
